name: Build Mod
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build Geode Mod
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Mod
      uses: geode-sdk/build-geode-mod@main
      id: build-step
      with:
        bindings: geode-sdk/bindings
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-custom-mod
        path: ${{ steps.build-step.outputs.build-output }}
